"""Add dob to leads

Revision ID: 0da45dc17766
Revises: 919b253a99f1
Create Date: 2026-07-24 06:46:29.483219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da45dc17766'
down_revision: Union[str, None] = '919b253a99f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'dob')
    # ### end Alembic commands ###