"""add_whatsapp_messages_table

Revision ID: 2fd58aa070b3
Revises: 41ceea977445
Create Date: 2026-08-15 19:36:27.411747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd58aa070b3'
down_revision: Union[str, None] = '41ceea977445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True, comment='NULL if the phone number could not be matched to a lead'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='The sales rep who owns this conversation'),
    sa.Column('whatsapp_msg_id', sa.String(length=255), nullable=True, comment='Unique message ID from WhatsApp, used for dedup'),
    sa.Column('instance_name', sa.String(length=100), nullable=True, comment='Evolution API instance name (e.g. rep1_session)'),
    sa.Column('sender_phone', sa.String(length=50), nullable=False),
    sa.Column('receiver_phone', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction', create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True, comment='image | video | audio | document | null for text'),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('sent', 'delivered', 'read', 'failed', name='message_status', create_constraint=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_msg_id')
    )
    op.create_index('ix_wa_lead_timestamp', 'whatsapp_messages', ['lead_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_lead_id'), 'whatsapp_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_user_id'), 'whatsapp_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_user_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_lead_id'), table_name='whatsapp_messages')
    op.drop_index('ix_wa_lead_timestamp', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    # ### end Alembic commands ###