"""add_escalation_columns_tasks_appointments

Revision ID: 674127a079f1
Revises: 69b8be23fcf4
Create Date: 2026-07-25 02:13:28.056547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674127a079f1'
down_revision: Union[str, None] = '69b8be23fcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('manager_alerted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('admin_alerted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('manager_alerted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('manager_alerted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('admin_alerted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'admin_alerted')
    op.drop_column('tasks', 'manager_alerted_at')
    op.drop_column('tasks', 'manager_alerted')
    op.drop_column('appointments', 'admin_alerted')
    op.drop_column('appointments', 'manager_alerted_at')
    # ### end Alembic commands ###