"""Add requested_end_time to task_due_date_requests

Revision ID: 69b8be23fcf4
Revises: 8afddee0dd73
Create Date: 2026-07-25 00:16:51.589075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b8be23fcf4'
down_revision: Union[str, None] = '8afddee0dd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_due_date_requests', sa.Column('requested_end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_due_date_requests', 'requested_end_time')
    # ### end Alembic commands ###