"""add_client_classification_to_leads

Revision ID: 919b253a99f1
Revises: h3i4j5k6l7m8
Create Date: 2026-07-22 23:32:53.158896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '919b253a99f1'
down_revision: Union[str, None] = 'h3i4j5k6l7m8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='upcoming | pending | completed',
               existing_nullable=False,
               existing_server_default=sa.text("'upcoming'::character varying"))
    op.alter_column('lead_ai_insights', 'insight_type',
               existing_type=sa.VARCHAR(length=50),
               comment="'score' | 'contact_timing' | future types",
               existing_nullable=False)
    op.alter_column('lead_ai_insights', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='Full structured result from the AI feature (LeadScoreResult dict, etc.)',
               existing_nullable=False)
    op.alter_column('lead_ai_insights', 'model_used',
               existing_type=sa.VARCHAR(length=100),
               comment="Gemini model name used for this run (e.g. 'gemini-2.0-flash')",
               existing_nullable=False)
    op.alter_column('lead_timeline', 'user_id',
               existing_type=sa.INTEGER(),
               comment='NULL for system-generated entries (e.g. SEO web form intake)',
               existing_nullable=True)
    op.execute("ALTER TABLE leads ADD COLUMN IF NOT EXISTS client_classification VARCHAR(20);")
    op.execute("ALTER TABLE leads ADD COLUMN IF NOT EXISTS client_classification_updated_at TIMESTAMPTZ;")
    op.alter_column('leads', 'ai_score_label',
               existing_type=sa.VARCHAR(length=10),
               comment="'hot' | 'warm' | 'cold' — mirrors latest LeadAIInsight.payload.label",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'ai_score_label',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment="'hot' | 'warm' | 'cold' — mirrors latest LeadAIInsight.payload.label",
               existing_nullable=True)
    op.drop_column('leads', 'client_classification_updated_at')
    op.drop_column('leads', 'client_classification')
    op.alter_column('lead_timeline', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='NULL for system-generated entries (e.g. SEO web form intake)',
               existing_nullable=True)
    op.alter_column('lead_ai_insights', 'model_used',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Gemini model name used for this run (e.g. 'gemini-2.0-flash')",
               existing_nullable=False)
    op.alter_column('lead_ai_insights', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment=None,
               existing_comment='Full structured result from the AI feature (LeadScoreResult dict, etc.)',
               existing_nullable=False)
    op.alter_column('lead_ai_insights', 'insight_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="'score' | 'contact_timing' | future types",
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='upcoming | pending | completed',
               existing_nullable=False,
               existing_server_default=sa.text("'upcoming'::character varying"))
    # ### end Alembic commands ###