"""add_due_date_requests_and_notifications

Revision ID: b333584e9b54
Revises: a1b2c3d4e5f6
Create Date: 2026-07-08 17:06:29.027601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b333584e9b54'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE IF NOT EXISTS notifications (
        id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        message TEXT NOT NULL,
        is_read BOOLEAN NOT NULL DEFAULT FALSE,
        link_type VARCHAR(50),
        link_id INTEGER,
        created_at TIMESTAMPTZ NOT NULL
    );
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications(user_id);")
    op.execute("""
    CREATE TABLE IF NOT EXISTS task_due_date_requests (
        id SERIAL PRIMARY KEY,
        task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
        requested_by_id INTEGER NOT NULL REFERENCES users(id),
        manager_id INTEGER NOT NULL REFERENCES users(id),
        requested_date DATE NOT NULL,
        reason TEXT NOT NULL,
        status VARCHAR(50) NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        resolved_at TIMESTAMPTZ
    );
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_task_due_date_requests_task_id ON task_due_date_requests(task_id);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_due_date_requests_task_id'), table_name='task_due_date_requests')
    op.drop_table('task_due_date_requests')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###