"""add_title_and_type_to_notifications

Revision ID: dc6d67a82907
Revises: b333584e9b54
Create Date: 2026-07-09 11:12:37.207038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6d67a82907'
down_revision: Union[str, None] = 'b333584e9b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE notifications ADD COLUMN IF NOT EXISTS title VARCHAR(255);")
    op.execute("ALTER TABLE notifications ADD COLUMN IF NOT EXISTS notification_type VARCHAR(100);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###